### ISSUE TITLE
Group Concensus

### ISSUE THREAD

**Issue by smeagle42** [JPII/NavalBattle#150]
1. Find a Leader
2. Find a direction
3. RT v. TBT

**Comment by abauer** [comment]
Easy, 1) = Thomas and Me, as we created original content.
2. We are using the Net Force Vector as our magnitude and direction
3) obviously we can only do Turn-Based because our memory usage only allows for it as-well-as our entire game design document is based on turn-based.

**Comment by ThomasGaubert** [comment]
My two cents:
1. A leader isn't necessary with the current structure. Each person is the lead of a different element of the entire game. If something that affects multiple parts of the game comes up, the appropriate leaders can work together (or whatever) and a vote can be called if need be. Having a single leader also has the potential to introduce issues.
2. Determined and outlined in the current roadmap.
3. Turn-based gameplay has been decided for quite some time.

Also this is mislabled, so fixed (not blocking progress of a milestone).

**Comment by ThomasGaubert** [comment]
In addition, I will add the following about gameplay and direction:

We have had the idea for gameplay and direction for the past five months. Each member has had access to the NavalBattle Design document. After being revised multiple times, we as a group majority came up with the current gameplay outline. This outline was reviewed as a group once again, with another chance for suggestions and changes.

As far as direction specifically goes, we outlined this in our roadmap this week. Suggestions and questions were once again accepted.

This whole thing is a waste of time. We have four months to make this game and you are worrying about petty details that were determined months ago.

**Comment by abauer** [comment]
As Thomas says 1 we can work issues out between leads, and questions can be discussed in the skype group.
2 the whole purpose of roadmap/milestones/issues is?
3 I completely agree with thomas in every aspect of his argument.

**Comment by ThomasGaubert** [comment]
I'd like to have other members weigh in on this.

cc: @DarkWarHero @Matthis5point0 @maximusvladimir @smeagle42

**Comment by maximusvladimir** [comment]
So after I slept on what we talked about the other day, thought about a few things.
1. I kinda agree with Thomas on this. A little story (Thomas may not like me telling this :wink:): so basically around 6th grade, Thomas and Alex made this thing called ChannelOne. Basically it was a "company" that we made to make like comedy videos or something. It would have been a really cool idea, but essentially the problem was that we never got anything done, because we were always arguing who should be "president". So basically I agree with Thomas-lets make this a democracy and not a dictatorship.
2. I think that we should focus on the milestones, but I think that we shouldn't limit ourselves to it, for example, if we are working on something, and really quickly we can add a feature that is in a future milestone, go ahead and add it. Or if there is something that you can add really quickly that is really cool, you should go ahead and add it (like that nifty System.out.println thing I did the other day.).
3. Anthony does make a very good point about real-time games, we would utilize much more CPU and memory than a turn-based game. Essentially I don't care which one y'all wanna do (but I am leaning towards TBT more), but we need to make the decision final before I start adding more features.

**Comment by ThomasGaubert** [comment]
In reply to @maximusvladimir:
1. Yeah I remember that and I want to avoid it again if possible. Democracy works best and we do not have time to restructure.
2. I completely agree. Milestones act as both due dates and a list of tasks to complete if you have nothing to do. Not having a structured roadmap didn't work for us in the past months, either.
3. I agree again, a real-time game is "too much effort" and not what we decided on, once again.

**Comment by maximusvladimir** [comment]
Agreed.

So hopefully this will help:

https://github.com/JPII/NavalBattle/wiki/Weekly-Goals

**Comment by ThomasGaubert** [comment]
If anyone would like this reopened, please feel free to (and supply commentary), otherwise this is a distraction from real work that needs to be done.
