### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by smeagle42** [JPII/NavalBattle#180]

**Comment by abauer** [comment]
no thats not how that works,
1) he wouldn't just copy it
2) its open source, anybody can view the source code.

**Comment by ThomasGaubert** [comment]
As mentioned by @abauer, this is not needed because we are open source. The source code is released under license and it is free for use under the terms of said license.

Also to accuse a teacher of willing to steal a project is a bit much.

**Comment by maximusvladimir** [comment]
1. Obtaining a copyright takes a while time to get.
2. It is open source so technically it is allowed. He could modify it and sell it if he wanted to (I am pretty sure he is allowed to do that).
3. We aren't EA, id Tech, or Microsoft Studios, this is purely for fun (and for a grade :wink:). We don't need to "copyright" it.

If y'all would be interested in making a closed source, commercial video game together in the future, I would be more than happy to participate in it (at a professional degree, not a secretive, mysterious "Pavo" coding degree). This just isn't the game for "closed sourceness".

**Comment by maximusvladimir** [comment]
If you are really worried, we can always do more "mysterious" code (code that is not perfectly clear), like I do, to avoid people from understanding it, and therefore vetoing their ability to change it.

**Comment by abauer** [comment]
no
id rather have more open code, or non-vague code;
yes i wouldn't mind working with @maximusvladimir on a professional degree

**Comment by maximusvladimir** [comment]
I have a "few" words to say about "yes i wouldn't mind working with @maximusvladimir on a professional degree", because I don't know how you meant it.

If you are referring to "I would rather have be working with a more professional version of Max", these are my comments:
A person once said: "If you are not happy with the current version of Max you are running, run a software upgrade, or find a new operating system." I might have mentioned this before, but Max likes money. If someone says "code this, for $<amount that pleases max, or greater than>, I will do it, and there will be full documentation, fast, reliable code, speedy results, good performance, as well as nice programs. The reason NavalBattle doesn't get my full attention is mainly for three reasons:
1. It's in Java. Although Java is a nice language itself (as in structure in syntax), but the JVM is terrible. Also, this is why Android Java > Desktop Java.
2. I am still attending school (barely though :wink:).
3. NavalBattle != money. (Android NavalBattle could = money though...)

If you are referring to "I would like to work with Max in the future on a closed-source commercial game":

I would very much like to too.

**Comment by ThomasGaubert** [comment]
Commerical NavalBattle Mobile would be something of interest, but we can't look to far ahead... :P
