### ISSUE TITLE
Art Style

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#247]
**Please leave unassigned and without a milestone as this is for discussion only. Do not close.**

---

Recent commits have raised the issue of art assets in the game. Let's dissect this issue.
### Disclaimer

As this is an aesthetic change, please try to keep discussion constructive and factual. Avoid subjective remarks (or label them as such) since they add little value to a group consensus.
### The Problem

As of posting this (0940aa3c8088974b898b6d439462293970eb07cb), the art of the game is as follows:

![art](https://f.cloud.github.com/assets/406075/423261/23b7e062-ad50-11e2-91b8-7c3bfbca8a10.PNG)

Let's address each asset individually (note that this isn't all the assets, but communicates the point):
- **A** - land is slightly pixelated, with gradients
- **B** - ports are blocky and simplistic
- **C** - whales are cartoon-like, on the verge of being pixelated
- **D** - aircraft carrier is photorealistic (or at least of higher detail)
- **E** - submarine is cartoon-like, more so than the whale
- **F** - OmniMap is only somewhat pixelated
- **G** - HUD is flat with some gradients for the buttons

In case you haven't noticed, the art assets are clashing by being a mix of cartoon, pixel art, and high detail.
### The Solution

First we need to come to a consensus on the art style of NavalBattle. After deciding this, we can address each asset individuality to determine what modifications are necessary. 

Discussion should occur here or in person (and recorded here).
### Conclusion

It's a problem and should be addressed. It's okay for changes like these to occur in the release candidates (but before launch!). 

I'm not saying who or what is right, just that there is an issue that needs to be addressed.

---

attn: @abauer @DarkWarHero @Matthis5point0 @smeagle42 @maximusvladimir

**Comment by ThomasGaubert** [comment]
In my opinion, the art style should be more towards the cartoon/pixel art/retro side of things because it is much easier to pull of that art style and because the terrain already has a similar feel. 

Having more realistic terrain is probably more effort than it's worth (especially considering deadlines).

**Comment by abauer** [comment]
I believe the way the land / water looks right now is of the best. It provides a realistic view of changing landmasses / water depths and also provides a look that is pixelated to keep to a theme

**Comment by maximusvladimir** [comment]
"I believe the way the land / water looks right now is of the best. It provides a realistic view of changing landmasses / water depths and also provides a look that is pixelated to keep to a theme"

Well at least somebody appreciates my work. :blush: .

In all seriousness, Thomas had made a very good point.
"Having more realistic terrain is probably more effort than it's worth (especially considering deadlines)."
Honestly, we originally had the pixelated terrain, because we were generating the terrain in real-time. This isn't the case anymore, so we could theoretically have a really pretty terrain like (without being pixelated of course):

![nice terrain](http://www.rigsofrods.com/wiki/images/3/37/Terrain_finishing_17.png)

I will admit, graphically, the new entity images are nice, however there is a inconstancy between entities, terrain, GUI, and font.
I believe that we should:
1. Aim for something photorealistic (like the above image, and the air craft carrier).
2. Aim for something pixelated and slightly cartoon-ish (like the current terrain, the whales, and the GUI).

Ultimately, I am siding for #2, because we are already almost there.

(Note: If we were to pick #1, chunk generation times could double, but the length it takes to render might be cut in half (a good thing), but also _might_ (not a definite) consume more memory).

**Comment by maximusvladimir** [comment]
PS:
AirBattle is going to have a 3D, photo-realistic terrain. It will automatically adjust based on graphics card power (e.g., if you have a strong graphics card, it will be a very detailed terrain, as opposed to a simple terrain, kinda like how it is in NavalBattle currently).

**Comment by maximusvladimir** [comment]
Also, we could see potential waves in a photo-realistic terrain, however, they will not be animated.

**Comment by JVetus** [comment]
Hi Matt,

I prefer simple and cartoon-like

**Comment by maximusvladimir** [comment]
I am considering doing a fork, just to experiment with photo-realistic terrains (after we close 0.8, of course).

**Comment by abauer** [comment]
how about after we close 1.0.0?

**Comment by ThomasGaubert** [comment]
Agree. Doing a fork now will only cause problems between now and merging back into the main branch due to changes leading up to release.

**Comment by maximusvladimir** [comment]
Oh I have no intention whatsoever of merging it back into the main branch. I think we should probably keep the cartoon/pixelated style. I just wanted to do a test (for curiosity reasons).

**Comment by ThomasGaubert** [comment]
Oh okay.

**Comment by maximusvladimir** [comment]
Have we come to consensus on this?

**Comment by ThomasGaubert** [comment]
Yes, I believe so. This will stay open until the art style has actually been unified.

**Comment by maximusvladimir** [comment]
Has the art style been unificated?

**Comment by ThomasGaubert** [comment]
I don't believe so...

cc: @smeagle42

**Comment by ThomasGaubert** [comment]
This has been resolved.
