### ISSUE TITLE
Memory Limit

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#62]
I don't know how serious the issue is at the moment, but apparently we have hit the memory allocation limit once or twice. 

If it's common now it won't get any less common as development continues.

This is more for discussion than an actual fix, at the moment.

**Comment by maximusvladimir** [comment]
Honestly, I have hit it many times. The issue is when the Game constructor is called (in otherwords when the terrain, grid, and other generation is going on). I can free up ALOT of memory if we make some more static variables. For example, currently every Entity has its own image, 3072 entities (64*48 = 3072), which is alot of images. If some of these images were shared with each other, we could decrease memory usage significantly. Technically, each image is about 80000 bytes which is about 245760000 bytes (234.375 MB) :exclamation:  that we are wasting. We only need 160000 bytes of memory, because we currently only have 2 entity images.

Additionally, calling the Garbage Collector :collision: after the Game() constructor should help a little. I also think that disposing the windows, which you should do, and NEVER override the dispose method (the dispose method is called internally by java, so you are technically messing with the internal workings of Java when you do this. You should call super.dispose() at least (you might be, idk). And then once they are disposed, we should set them to null, so that the Garbage gets taken out.

Also sound (cough cough) uses up a significant amount of memory. 

BTW, I don't know if any of this is right, but it is just a suggestion. :tongue:

**Comment by maximusvladimir** [comment]
Oh I am sorry. Each image is 20000 bytes, so we are currently occupying only 61440000 bytes (58.59375 MB). We actually only need 40000 bytes.

**Comment by ThomasGaubert** [comment]
Allowing the images of entities to be shared while still allowing for unique characteristics such as color should be feasible.

I thought you warned against disposing windows? (or was that only if you were going to just recall them again?) If we can, we should clean out as many windows as we can once they aren't needed... namely Login and LoggingIn windows.

We can make sure that there is enough optimization to run at the current milestone (basically it shouldn't crash) and focus on optimizations on the next milestone.

**Comment by ThomasGaubert** [comment]
@abauer needs to look at this.

**Comment by maximusvladimir** [comment]
yeah. @abauer needs to look at it. You _should_ dispose windows, just as long as you aren't going to use them anymore.

**Comment by ThomasGaubert** [comment]
Okay, that's what I thought.

**Comment by abauer** [comment]
i think we are currently disposing windows, and i belive i am calling super.dispose();
taking a look right now

**Comment by abauer** [comment]
correction, login window and loggingin window are both disposed, the disposed method is never overwritten but super.dispose(); is called...

**Comment by abauer** [comment]
we could have an entity manager for every type of entitiy and have one static image use-able by all, then when u need to draw each entity they can be drawn by their manager.

**Comment by abauer** [comment]
what else needs to be done to finish this milestone?

**Comment by ThomasGaubert** [comment]
Nothing probably at the moment, as we haven't even added the battleship images, etc.

When we add them we need to start with a logical image manager, etc.

**Comment by abauer** [comment]
plus we might be refactoring

**Comment by maximusvladimir** [comment]
Wait why is this closed??? The problem is still present.

**Comment by ThomasGaubert** [comment]
It's going to be handled as we move forward (as we can't really do much at the moment until we have stuff to manage). It can be reopened if needed.

**Comment by maximusvladimir** [comment]
Oh ok. I see. So basically this is a reoccurring issue, but we've fixed it for now.

**Comment by ThomasGaubert** [comment]
Correct.

**Comment by maximusvladimir** [comment]
So this is kind of an issue with WorldSize.WORLD_HUGE maps. It cuts it very close to the JVM limit.
