### ISSUE TITLE
Battleships implemented

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#65]
implement battleships to the grid, not all bells and whistles needed

**Comment by maximusvladimir** [comment]
This is not going to be done before Pavo is done... and Pavo is due in 0.5.

**Comment by abauer** [comment]
um ok... moved to milestone 0.5

**Comment by ThomasGaubert** [comment]
Ouch... 0.5 will be a big milestone.

**Comment by maximusvladimir** [comment]
:frowning:

**Comment by ThomasGaubert** [comment]
This will be locked in for Milestone 0.5 and cannot be moved unless in an extreme case.

**Comment by maximusvladimir** [comment]
Agreed.

**Comment by abauer** [comment]
is this done?
they are technically in the game

**Comment by ThomasGaubert** [comment]
Uh yeah, I guess so. Separate issues will be made for features.

**Comment by maximusvladimir** [comment]
Woah woah woah.... Battleships are NOT in the game. Consider them the same as the tanks-they are here strictly for testing. PavoGrid is not even in Alpha stage. It is in like conception stage.

**Comment by ThomasGaubert** [comment]
Ugh, re-opened.

We need to move PavoGrid into Alpha, let alone ready for production. Remember, 4 months (not including QA)!

**Comment by maximusvladimir** [comment]
Pavo is no where near being ready for Alpha!

Pavo's future:
1. 2 modes for terrain, you can use images, or use the default color generator for the pixels.
2. Customisable terrain (e.g. change colors (kinda applies to above), add more water, add buildings, etc).
3. Isometric mode. Pavo will be able to render in either isometric mode or overhead view (current).
4. Fast updates.
5. The ability to run on the GPU instead of the CPU for rendering (allows for reflective water, lighting systems, realtime rendering, etc).
6. Relative tile tick (allows ticking of entities/tiles based on distance from screen).
7. Virtually unlimited terrain size and virtually unlimited entities (like Minecraft).
8. Better Window API.
9. Themes for Windows/GUI.
10. Animated water in CPU mode.
11. ©KeenEdge rendering.
12. Bluring and better animation.

I expect to roll all this out in NavalBattle 0.9. Then we will move Pavo to its own package.

**Comment by ThomasGaubert** [comment]
So we are finishing the engine on the second to last milestone that isn't featured locked? Bad pacing, no?

To be clear, version 1.0 is what we are turning in at the end of May.

**Comment by maximusvladimir** [comment]
Those are the long time features of Pavo. I don't expect to see many of them in NavalBattle 1.0.

**Comment by ThomasGaubert** [comment]
Okay I understand now.

**Comment by abauer** [comment]
As long as we finish!

**Comment by maximusvladimir** [comment]
We will finish.
